include:
  - template: Auto-DevOps.gitlab-ci.yml

test:
  services:
   - name: mongo:4.2.2
     alias: mongodb
   - redis:latest
  stage: test
  image: gliderlabs/herokuish:latest
  script:
    - cp config.example.ts config.ts
    - cp -R . /tmp/app
    - /bin/herokuish buildpack test
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
